# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gTB_ASR.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgTB_ASR.proto\x12\x07gTB_ASR\"\x1f\n\x0f\x46ilenameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x08\x41SRReply\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\nWavRequest\x12\x0b\n\x03wav\x18\x01 \x01(\x0c\"\x0f\n\rAgentsRequest\"\x1d\n\x0b\x41gentsReply\x12\x0e\n\x06\x61gents\x18\x01 \x03(\t\"#\n\x0f\x41\x64\x64\x41gentRequest\x12\x10\n\x08\x61gent_ip\x18\x01 \x01(\t\"\x1f\n\rAddAgentReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\xf7\x01\n\x07gTB_ASR\x12\x38\n\x07\x41SRFile\x12\x18.gTB_ASR.FilenameRequest\x1a\x11.gTB_ASR.ASRReply\"\x00\x12\x32\n\x06\x41SRWav\x12\x13.gTB_ASR.WavRequest\x1a\x11.gTB_ASR.ASRReply\"\x00\x12;\n\tASRAgents\x12\x16.gTB_ASR.AgentsRequest\x1a\x14.gTB_ASR.AgentsReply\"\x00\x12\x41\n\x0b\x41SRAddAgent\x12\x18.gTB_ASR.AddAgentRequest\x1a\x16.gTB_ASR.AddAgentReply\"\x00\x42\x12Z\x10gToolbox/gTB_ASRb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gTB_ASR_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020gToolbox/gTB_ASR'
  _globals['_FILENAMEREQUEST']._serialized_start=26
  _globals['_FILENAMEREQUEST']._serialized_end=57
  _globals['_ASRREPLY']._serialized_start=59
  _globals['_ASRREPLY']._serialized_end=83
  _globals['_WAVREQUEST']._serialized_start=85
  _globals['_WAVREQUEST']._serialized_end=110
  _globals['_AGENTSREQUEST']._serialized_start=112
  _globals['_AGENTSREQUEST']._serialized_end=127
  _globals['_AGENTSREPLY']._serialized_start=129
  _globals['_AGENTSREPLY']._serialized_end=158
  _globals['_ADDAGENTREQUEST']._serialized_start=160
  _globals['_ADDAGENTREQUEST']._serialized_end=195
  _globals['_ADDAGENTREPLY']._serialized_start=197
  _globals['_ADDAGENTREPLY']._serialized_end=228
  _globals['_GTB_ASR']._serialized_start=231
  _globals['_GTB_ASR']._serialized_end=478
# @@protoc_insertion_point(module_scope)
